services:
  seasonarr:
    image: ghcr.io/d3v1l1989/seasonarr:latest
    container_name: seasonarr
    restart: unless-stopped
    hostname: seasonarr
    platform: linux/amd64
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DATABASE_URL=sqlite:///./data/seasonarr.db
      - JWT_SECRET_KEY=change-this-to-a-secure-random-string
    volumes:
      - seasonarr_data:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
    networks:
      - sonarrNetwork

volumes:
  seasonarr_data:

networks:
  sonarrNetwork:
    external: true